version: '2'

services:
  server:
    container_name: server
    build: .
    restart: always
    environment:
      - NODE_ENV=production
      - TZ=Asia/Seoul
      - STEEMKR_VERSION=stable
    restart: always
    ports:
      - 3021:8080
    depends_on:
      - steemkr_mysql
