version: '2'

services:
  beta:
    container_name: beta
    build: .
    restart: always
    environment:
      - NODE_ENV=production
      - TZ=Asia/Seoul
      - STEEMKR_VERSION=beta
    restart: always
    ports:
      - 3001:8080
    depends_on:
      - steemkr_mysql
